default:
	lessc -x blk.less blk.css
	lessc -x index.less index.css
	lessc -x sign.less sign.css
	lessc -x proset.less proset.css
	lessc -x pro.less pro.css
	lessc -x submit.less submit.css
	lessc -x acct.less acct.css
	lessc -x scbd.less scbd.css
	lessc -x board.less board.css
	lessc -x manage-pro.less manage-pro.css
	lessc -x challist.less challist.css
