x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "2"

services:
  backend:
    build:
      context: ./
      target: release
      args:
        DB_PASSWORD: $DB_PASSWORD
        UNLOCK_PASSWORD: $UNLOCK_PASSWORD
        TIMEDELTA: $TIMEDELTA
        SITE_TITLE: $SITE_TITLE
        ADMIN_NAME: $ADMIN_NAME
        ADMIN_MAIL: $ADMIN_MAIL
        ADMIN_PASSWORD: $ADMIN_PASSWORD
        BASE_URL: $BASE_URL
    volumes:
      - /srv/ntoj/static:/ntoj/static
      - /srv/ntoj/problem:/ntoj/problem
      - /srv/ntoj/code:/ntoj/code
      # - /srv/ntoj/config.py:/ntoj/config.py
    depends_on:
      - db
      - cache
    networks:
      - app
      - judge_net
    ports:
      - "5500:5500"
    logging: *default-logging

  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ntoj
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ntoj
    volumes:
      - /srv/ntoj/db:/var/lib/postgresql/18/docker
    networks:
      - app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ntoj -d ntoj"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging: *default-logging

  cache:
    image: redis:8-alpine
    volumes:
      - /srv/ntoj/cache:/data
    networks:
      - app
    logging: *default-logging

  judge:
    build: https://github.com/tobiichi3227/NTOJ-Judge-Rewrite.git
    cap_add:
      - MKNOD
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_RESOURCE
    cgroup: host
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - label:disable
    tmpfs:
      - /dev/shm:rw,exec,size=755,size=4G
    volumes:
      - /srv/ntoj/problem:/problem:ro
      - /srv/ntoj/code:/code:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      - judge_net

    privileged: true
    logging: *default-logging

networks:
  app:
  judge_net:
