[tool.poetry]
name = "ntoj"
version = "v2.1.2"
description = "New TNFSH Online Judge"
authors = [
    "LifeAdventurer <life0adventurer@gmail.com>",
    "tobiichi3227 <cz1346219@gmail.com>"
]
package-mode = false
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
tornado = ">=6.5.1"
asyncpg = ">=0.30.0"
redis = ">=6.2.0"
msgpack = ">=1.1.1"
bcrypt = ">=4.3.1"
termcolor = "^2.3.0"
mkdocs-material = "^9.5.13"
natsort = "^8.4.0"


[tool.poetry.group.dev.dependencies]
black = ">=25.1.0"
isort = ">=6.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
skip-string-normalization = true

[tool.isort]
profile = "black"
