name: tests
on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.14

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install PostgreSQL, Redis, Dos2Unix, CJK Font
        run: |
          sudo curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | sudo tee /usr/share/keyrings/postgresql.gpg
          echo deb [arch=amd64 signed-by=/usr/share/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main | sudo tee /etc/apt/sources.list.d/postgresql.list
          sudo apt update -y
          sudo apt install -f -y postgresql-16 postgresql-client-16 redis dos2unix fonts-noto-cjk
          sudo sed -i 's/peer/trust/g' /etc/postgresql/16/main/pg_hba.conf
          sudo sed -i 's/scram-sha-256/trust/g' /etc/postgresql/16/main/pg_hba.conf
          sudo service postgresql restart
          sudo service redis-server restart

      - name: Install Project dependencies and test requirements
        run: |
          sed -i '/^mkdocs-material/d' pyproject.toml # test don't need mkdocs-material
          $HOME/.local/bin/poetry lock # we need to update lockfile because we change the pyproject file
          $HOME/.local/bin/poetry install
          $HOME/.local/bin/poetry add --dev coverage
          $HOME/.local/bin/poetry add beautifulsoup4
          $HOME/.local/bin/poetry add requests

      - name: Deploy NTOJ-Judge
        run: |
          cd $HOME
          git clone https://github.com/tobiichi3227/NTOJ-Judge-Rewrite
          cd NTOJ-Judge-Rewrite/src
          cd default-checker && make -j4 && cd ..
          sudo pip3 install tornado cffi --break-system-packages
          sudo python3 server.py > output.log 2>&1 &

      - name: Run Unit Test
        run: |
          cd src
          chmod +x rununittest.sh
          ./rununittest.sh

      - name: Upload Unit Test Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage-report
          path: src/htmlcov

      - name: Run Integrated Test
        run: |
          cd src
          chmod +x runintegratedtest.sh
          ./runintegratedtest.sh

      - name: Output judge log
        run: |
          cd $HOME/NTOJ-Judge-Rewrite/src
          cat output.log

      - name: Upload Integrated Test Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: integrated-test-coverage-report
          path: src/htmlcov
